"""Vivado backend: render an :class:`EdaDesign` into a source ``.tcl`` script.

Vivado is driven by Tcl. We emit ``<name>.tcl`` that reads each source with the
right command (``read_verilog -sv`` / ``read_verilog`` / ``read_vhdl``), sets the
top module on the current fileset, and updates the compile order. Unlike Verilator
this backend accepts all three HDLs; an unrecognized file type is a hard error.
"""

from __future__ import annotations

from .base import Backend, GeneratedFiles
from .edam import EdaDesign

__all__ = ["VivadoBackend"]

# Normalized file kind -> the Vivado Tcl read command.
_READ_COMMAND = {
    "systemVerilog": "read_verilog -sv",
    "verilog": "read_verilog",
    "vhdl": "read_vhdl",
}
_SUPPORTED = frozenset(_READ_COMMAND)


class VivadoBackend(Backend):
    """Generate a Vivado source ``.tcl`` script."""

    name = "vivado"

    def generate(self, design: EdaDesign) -> GeneratedFiles:
        self._reject_unsupported(design, _SUPPORTED)

        lines = [f"# Vivado source script for {design.name} (generated by hdlpkg gen)."]
        for f in design.files:
            lines.append(f'{_READ_COMMAND[f.file_type]} "{f.path}"')
        if design.toplevel is not None:  # the Vivado script's top is optional
            lines.append(
                f"set_property top {self._validated_top(design.toplevel)} [current_fileset]"
            )
        lines.append("update_compile_order -fileset [current_fileset]")
        return {f"{design.name}.tcl": "\n".join(lines) + "\n"}
