"""GHDL backend: a run script that analyzes, elaborates, and runs VHDL.

GHDL is a VHDL simulator driven by ``ghdl -a`` (analyze) / ``-e`` (elaborate) /
``-r`` (run). We emit a ``run_ghdl.sh`` that does all three for the design's files
and top. GHDL is VHDL-only, so any (System)Verilog source is a hard error.
"""

from __future__ import annotations

from ..exceptions import BackendError
from .base import Backend, GeneratedFiles
from .edam import EdaDesign

__all__ = ["GhdlBackend"]

_SUPPORTED = frozenset({"vhdl"})


class GhdlBackend(Backend):
    """Generate a GHDL analyze/elaborate/run script."""

    name = "ghdl"

    def generate(self, design: EdaDesign) -> GeneratedFiles:
        if design.toplevel is None:
            raise BackendError(
                f"GHDL needs a top unit, but target for {design.name!r} declares none."
            )
        unsupported = sorted({f.file_type for f in design.files if f.file_type not in _SUPPORTED})
        if unsupported:
            raise BackendError(
                f"GHDL only compiles VHDL, but the design has file type(s) "
                f"{', '.join(unsupported)}."
            )

        files = " ".join(f'"{f.path}"' for f in design.files)
        script = (
            "#!/bin/sh\n"
            f"# GHDL build for {design.name} (generated by hdlpkg gen).\n"
            f"ghdl -a --std=08 {files}\n"
            f"ghdl -e --std=08 {design.toplevel}\n"
            f"ghdl -r --std=08 {design.toplevel}\n"
        )
        return {"run_ghdl.sh": script}
