"""GHDL backend: a run script that analyzes, elaborates, and runs VHDL.

GHDL is a VHDL simulator driven by ``ghdl -a`` (analyze) / ``-e`` (elaborate) /
``-r`` (run). We emit a ``run_ghdl.sh`` that does all three for the design's files
and top. GHDL is VHDL-only, so any (System)Verilog source is a hard error.
"""

from __future__ import annotations

from .base import Backend, GeneratedFiles
from .edam import EdaDesign

__all__ = ["GhdlBackend"]

_SUPPORTED = frozenset({"vhdl"})


class GhdlBackend(Backend):
    """Generate a GHDL analyze/elaborate/run script."""

    name = "ghdl"

    def generate(self, design: EdaDesign) -> GeneratedFiles:
        top = self._require_top(design)
        self._reject_unsupported(design, _SUPPORTED)

        files = " ".join(f'"{f.path}"' for f in design.files)
        script = (
            "#!/bin/sh\n"
            f"# GHDL build for {design.name} (generated by hdlpkg gen).\n"
            f"ghdl -a --std=08 {files}\n"
            f"ghdl -e --std=08 {top}\n"
            f"ghdl -r --std=08 {top}\n"
        )
        return {"run_ghdl.sh": script}
