"""Icarus Verilog backend: a command file + a run script for ``iverilog``/``vvp``.

Icarus compiles (System)Verilog to a ``.vvp`` object run by ``vvp``. We emit a
command file (``<name>.cmd``, one source path per line — Icarus's ``-c`` input)
and a small ``run_iverilog.sh`` that compiles and runs it. Icarus does not handle
VHDL, so a VHDL source in the design is a hard error.
"""

from __future__ import annotations

from .base import Backend, GeneratedFiles
from .edam import EdaDesign

__all__ = ["IcarusBackend"]

_SUPPORTED = frozenset({"systemVerilog", "verilog"})


class IcarusBackend(Backend):
    """Generate Icarus Verilog inputs (a command file + a run script)."""

    name = "icarus"

    def generate(self, design: EdaDesign) -> GeneratedFiles:
        top = self._require_top(design)
        self._reject_unsupported(design, _SUPPORTED)

        command_file = "\n".join(f.path for f in design.files) + "\n"
        script = (
            "#!/bin/sh\n"
            f"# Icarus Verilog build for {design.name} (generated by hdlpkg gen).\n"
            f"iverilog -g2012 -s {top} -o {design.name}.vvp -c {design.name}.cmd\n"
            f"vvp {design.name}.vvp\n"
        )
        return {f"{design.name}.cmd": command_file, "run_iverilog.sh": script}
