"""Icarus Verilog backend: a command file + a run script for ``iverilog``/``vvp``.

Icarus compiles (System)Verilog to a ``.vvp`` object run by ``vvp``. We emit a
command file (``<name>.cmd``, one source path per line — Icarus's ``-c`` input)
and a small ``run_iverilog.sh`` that compiles and runs it. Icarus does not handle
VHDL, so a VHDL source in the design is a hard error.
"""

from __future__ import annotations

from ..exceptions import BackendError
from .base import Backend, GeneratedFiles
from .edam import EdaDesign

__all__ = ["IcarusBackend"]

_SUPPORTED = frozenset({"systemVerilog", "verilog"})


class IcarusBackend(Backend):
    """Generate Icarus Verilog inputs (a command file + a run script)."""

    name = "icarus"

    def generate(self, design: EdaDesign) -> GeneratedFiles:
        if design.toplevel is None:
            raise BackendError(
                f"Icarus needs a top module, but target for {design.name!r} declares none."
            )
        unsupported = sorted({f.file_type for f in design.files if f.file_type not in _SUPPORTED})
        if unsupported:
            raise BackendError(
                f"Icarus Verilog cannot compile file type(s) {', '.join(unsupported)}; "
                f"it supports {', '.join(sorted(_SUPPORTED))}."
            )

        command_file = "\n".join(f.path for f in design.files) + "\n"
        script = (
            "#!/bin/sh\n"
            f"# Icarus Verilog build for {design.name} (generated by hdlpkg gen).\n"
            f"iverilog -g2012 -s {design.toplevel} -o {design.name}.vvp -c {design.name}.cmd\n"
            f"vvp {design.name}.vvp\n"
        )
        return {f"{design.name}.cmd": command_file, "run_iverilog.sh": script}
