"""Verilator backend: render an :class:`EdaDesign` into a ``.vc`` command file.

Verilator consumes a *command file* (``-f file.vc``) listing the Verilog/
SystemVerilog sources and flags. We emit one ``<name>.vc`` with ``--top-module``
and the ordered source list. Verilator does not support VHDL, so a VHDL source in
the design is a hard error rather than a silently dropped file.
"""

from __future__ import annotations

from .base import Backend, GeneratedFiles
from .edam import EdaDesign

__all__ = ["VerilatorBackend"]

# File kinds Verilator can compile (see edam.normalize_file_type).
_SUPPORTED = frozenset({"systemVerilog", "verilog"})


class VerilatorBackend(Backend):
    """Generate a Verilator ``.vc`` command file."""

    name = "verilator"

    def generate(self, design: EdaDesign) -> GeneratedFiles:
        top = self._require_top(design)
        self._reject_unsupported(design, _SUPPORTED)

        lines = [
            f"// Verilator command file for {design.name} (generated by hdlpkg gen).",
            f"--top-module {top}",
        ]
        lines.extend(f.path for f in design.files)
        return {f"{design.name}.vc": "\n".join(lines) + "\n"}
