"""Verilator backend: render an :class:`EdaDesign` into a ``.vc`` command file.

Verilator consumes a *command file* (``-f file.vc``) listing the Verilog/
SystemVerilog sources and flags. We emit one ``<name>.vc`` with ``--top-module``
and the ordered source list. Verilator does not support VHDL, so a VHDL source in
the design is a hard error rather than a silently dropped file.
"""

from __future__ import annotations

from ..exceptions import BackendError
from .base import Backend, GeneratedFiles
from .edam import EdaDesign

__all__ = ["VerilatorBackend"]

# File kinds Verilator can compile (see edam.normalize_file_type).
_SUPPORTED = frozenset({"systemVerilog", "verilog"})


class VerilatorBackend(Backend):
    """Generate a Verilator ``.vc`` command file."""

    name = "verilator"

    def generate(self, design: EdaDesign) -> GeneratedFiles:
        if design.toplevel is None:
            raise BackendError(
                f"Verilator needs a top module, but target for {design.name!r} declares none."
            )
        unsupported = sorted({f.file_type for f in design.files if f.file_type not in _SUPPORTED})
        if unsupported:
            raise BackendError(
                f"Verilator cannot compile file type(s) {', '.join(unsupported)}; "
                f"it supports {', '.join(sorted(_SUPPORTED))}."
            )

        lines = [
            f"// Verilator command file for {design.name} (generated by hdlpkg gen).",
            f"--top-module {design.toplevel}",
        ]
        lines.extend(f.path for f in design.files)
        return {f"{design.name}.vc": "\n".join(lines) + "\n"}
