"""Vivado backend: render an :class:`EdaDesign` into a source ``.tcl`` script.

Vivado is driven by Tcl. We emit ``<name>.tcl`` that reads each source with the
right command (``read_verilog -sv`` / ``read_verilog`` / ``read_vhdl``), sets the
top module on the current fileset, and updates the compile order. Unlike Verilator
this backend accepts all three HDLs; an unrecognized file type is a hard error.
"""

from __future__ import annotations

from ..exceptions import BackendError
from .base import Backend, GeneratedFiles
from .edam import EdaDesign

__all__ = ["VivadoBackend"]

# Normalized file kind -> the Vivado Tcl read command.
_READ_COMMAND = {
    "systemVerilog": "read_verilog -sv",
    "verilog": "read_verilog",
    "vhdl": "read_vhdl",
}


class VivadoBackend(Backend):
    """Generate a Vivado source ``.tcl`` script."""

    name = "vivado"

    def generate(self, design: EdaDesign) -> GeneratedFiles:
        unsupported = sorted(
            {f.file_type for f in design.files if f.file_type not in _READ_COMMAND}
        )
        if unsupported:
            raise BackendError(
                f"Vivado backend cannot read file type(s) {', '.join(unsupported)}; "
                f"it supports {', '.join(sorted(_READ_COMMAND))}."
            )

        lines = [f"# Vivado source script for {design.name} (generated by hdlpkg gen)."]
        for f in design.files:
            lines.append(f'{_READ_COMMAND[f.file_type]} "{f.path}"')
        if design.toplevel is not None:
            lines.append(f"set_property top {design.toplevel} [current_fileset]")
        lines.append("update_compile_order -fileset [current_fileset]")
        return {f"{design.name}.tcl": "\n".join(lines) + "\n"}
