"""Yosys backend: a synthesis script (``.ys``) reading (System)Verilog sources.

Yosys is an open-source synthesis suite driven by a ``.ys`` script. We emit one
that reads each source, sets the hierarchy top, and runs generic synthesis. The
stock Yosys Verilog frontend does not read VHDL (that needs the ghdl-yosys plugin),
so a VHDL source is a hard error here.
"""

from __future__ import annotations

from .base import Backend, GeneratedFiles
from .edam import EdaDesign

__all__ = ["YosysBackend"]

# Normalized file kind -> the Yosys read command.
_READ_COMMAND = {
    "systemVerilog": "read_verilog -sv",
    "verilog": "read_verilog",
}
_SUPPORTED = frozenset(_READ_COMMAND)


class YosysBackend(Backend):
    """Generate a Yosys synthesis ``.ys`` script."""

    name = "yosys"

    def generate(self, design: EdaDesign) -> GeneratedFiles:
        top = self._require_top(design)
        self._reject_unsupported(design, _SUPPORTED)

        lines = [f"# Yosys synthesis script for {design.name} (generated by hdlpkg gen)."]
        for f in design.files:
            lines.append(f'{_READ_COMMAND[f.file_type]} "{f.path}"')
        lines.append(f"hierarchy -check -top {top}")
        lines.append(f"synth -top {top}")
        return {f"{design.name}.ys": "\n".join(lines) + "\n"}
