"""Yosys backend: a synthesis script (``.ys``) reading (System)Verilog sources.

Yosys is an open-source synthesis suite driven by a ``.ys`` script. We emit one
that reads each source, sets the hierarchy top, and runs generic synthesis. The
stock Yosys Verilog frontend does not read VHDL (that needs the ghdl-yosys plugin),
so a VHDL source is a hard error here.
"""

from __future__ import annotations

from ..exceptions import BackendError
from .base import Backend, GeneratedFiles
from .edam import EdaDesign

__all__ = ["YosysBackend"]

# Normalized file kind -> the Yosys read command.
_READ_COMMAND = {
    "systemVerilog": "read_verilog -sv",
    "verilog": "read_verilog",
}


class YosysBackend(Backend):
    """Generate a Yosys synthesis ``.ys`` script."""

    name = "yosys"

    def generate(self, design: EdaDesign) -> GeneratedFiles:
        if design.toplevel is None:
            raise BackendError(
                f"Yosys needs a top module, but target for {design.name!r} declares none."
            )
        unsupported = sorted(
            {f.file_type for f in design.files if f.file_type not in _READ_COMMAND}
        )
        if unsupported:
            raise BackendError(
                f"Yosys backend reads only Verilog/SystemVerilog; got file type(s) "
                f"{', '.join(unsupported)} (VHDL needs the ghdl-yosys plugin)."
            )

        lines = [f"# Yosys synthesis script for {design.name} (generated by hdlpkg gen)."]
        for f in design.files:
            lines.append(f'{_READ_COMMAND[f.file_type]} "{f.path}"')
        lines.append(f"hierarchy -check -top {design.toplevel}")
        lines.append(f"synth -top {design.toplevel}")
        return {f"{design.name}.ys": "\n".join(lines) + "\n"}
