"""The lockfile (``ip.lock``).

A lockfile is the generated, committed record of a resolve: the exact `Vlnv`
chosen for every package, plus an integrity `checksum` and the `source` it came
from. Committing it gives reproducible, verifiable builds -- the Cargo / Orbit /
Go model. It is the serialized form of a :class:`~hdlpkg.resolver.Resolution`.

The format is TOML (so it reads like ``ip.toml``), with a schema ``version`` and a
``[[package]]`` array sorted by VLNV for a stable, diff-friendly file::

    # Auto-generated by hdlpkg. Do not edit by hand.
    version = 1

    [[package]]
    vlnv     = "acme:common:fifo:1.0.0"
    source   = "path:examples/fifo"
    checksum = "sha256:..."

This module is pure: it serializes, parses, and verifies, but never reads the
cores it locks. Computing a core's checksum from its bytes is done by the caller
(the cache/registry layer) via :func:`sha256_digest`. At this milestone the CLI
fills ``checksum`` from the manifest bytes; M3 widens it to the full packaged
content without changing the file format.
"""

from __future__ import annotations

import hashlib
import tomllib
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path

from .exceptions import HdlPackagerError, LockfileError
from .manifest import Manifest
from .resolver import Resolution
from .version import (
    SUPPORTED_VERSION_SCHEMES,
    AnyVersion,
    CalVer,
    MonotonicVersion,
    OpaqueVersion,
    VersionScheme,
)
from .vlnv import PackageRef, Vlnv

__all__ = [
    "LOCKFILE_FILENAME",
    "LOCKFILE_VERSION",
    "LockedPackage",
    "Lockfile",
    "lock_satisfies_manifest",
    "sha256_digest",
]

LOCKFILE_FILENAME = "ip.lock"
LOCKFILE_VERSION = 1


def sha256_digest(data: bytes) -> str:
    """Return the canonical ``sha256:<hex>`` digest of *data*."""
    return f"sha256:{hashlib.sha256(data).hexdigest()}"


def _toml_basic_string(value: str) -> str:
    """Render *value* as a TOML basic (double-quoted) string, escaping specials."""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _scheme_marker(version: AnyVersion) -> VersionScheme | None:
    """The non-SemVer scheme to record for *version*, or None for plain SemVer."""
    if isinstance(version, OpaqueVersion):
        return "opaque"
    if isinstance(version, CalVer):
        return "calver"
    if isinstance(version, MonotonicVersion):
        return "monotonic"
    return None


@dataclass(frozen=True)
class LockedPackage:
    """One resolved package pinned in the lockfile: its VLNV, source, and checksum."""

    vlnv: Vlnv
    source: str = ""
    checksum: str = ""


@dataclass(frozen=True)
class Lockfile:
    """A parsed, validated ``ip.lock``: a schema version plus pinned packages."""

    packages: tuple[LockedPackage, ...]
    lockfile_version: int = LOCKFILE_VERSION

    @classmethod
    def from_resolution(
        cls,
        resolution: Resolution,
        sources: Mapping[Vlnv, str] | None = None,
        checksums: Mapping[Vlnv, str] | None = None,
    ) -> Lockfile:
        """Build a lockfile from a resolve, attaching any known source/checksum."""
        sources = sources or {}
        checksums = checksums or {}
        packages = tuple(
            LockedPackage(vlnv=vlnv, source=sources.get(vlnv, ""), checksum=checksums.get(vlnv, ""))
            for vlnv in resolution.vlnvs  # already sorted for determinism
        )
        return cls(packages=packages)

    # ------------------------------------------------------------- serialize
    def to_toml(self) -> str:
        """Render the lockfile as deterministic TOML text."""
        lines = [
            "# Auto-generated by hdlpkg. Do not edit by hand.",
            f"version = {self.lockfile_version}",
        ]
        for pkg in sorted(self.packages, key=lambda p: str(p.vlnv)):
            lines += ["", "[[package]]", f"vlnv     = {_toml_basic_string(str(pkg.vlnv))}"]
            marker = _scheme_marker(pkg.vlnv.version)
            if marker is not None:
                # Record a non-SemVer scheme so the version round-trips on parse.
                lines.append(f'scheme   = "{marker}"')
            if pkg.source:
                lines.append(f"source   = {_toml_basic_string(pkg.source)}")
            if pkg.checksum:
                lines.append(f"checksum = {_toml_basic_string(pkg.checksum)}")
        return "\n".join(lines) + "\n"

    # ----------------------------------------------------------------- parse
    @classmethod
    def from_toml(cls, text: str) -> Lockfile:
        """Parse a lockfile from TOML text; raise :class:`LockfileError` on failure."""
        try:
            data = tomllib.loads(text)
        except tomllib.TOMLDecodeError as exc:
            raise LockfileError(f"Invalid TOML in lockfile: {exc}") from exc

        version = data.get("version")
        if version != LOCKFILE_VERSION:
            raise LockfileError(
                f"Unsupported lockfile version {version!r}; expected {LOCKFILE_VERSION}."
            )

        raw_packages = data.get("package", [])
        if not isinstance(raw_packages, list):
            raise LockfileError("Lockfile 'package' must be an array of tables.")
        packages = tuple(cls._parse_package(entry) for entry in raw_packages)
        return cls(packages=packages, lockfile_version=version)

    @classmethod
    def from_path(cls, path: str | Path) -> Lockfile:
        """Parse a lockfile from disk."""
        path = Path(path)
        try:
            text = path.read_text(encoding="utf-8")
        except OSError as exc:
            raise LockfileError(f"Cannot read lockfile {path}: {exc}") from exc
        return cls.from_toml(text)

    @staticmethod
    def _parse_package(entry: object) -> LockedPackage:
        if not isinstance(entry, dict):
            raise LockfileError("Each [[package]] must be a table.")
        vlnv_str = entry.get("vlnv")
        if not isinstance(vlnv_str, str):
            raise LockfileError("Each [[package]] needs a 'vlnv' string.")
        raw_scheme = entry.get("scheme")
        scheme: VersionScheme = raw_scheme if raw_scheme in SUPPORTED_VERSION_SCHEMES else "semver"
        try:
            vlnv = Vlnv.parse(vlnv_str, scheme)
        except HdlPackagerError as exc:
            raise LockfileError(f"Invalid vlnv {vlnv_str!r} in lockfile: {exc}") from exc
        return LockedPackage(
            vlnv=vlnv,
            source=str(entry.get("source", "")),
            checksum=str(entry.get("checksum", "")),
        )

    # ------------------------------------------------------------- integrity
    def verify(self, checksums: Mapping[Vlnv, str]) -> None:
        """Check *checksums* against the locked ones; raise on any mismatch.

        Packages locked without a checksum are skipped (nothing to verify). A
        locked package whose checksum disagrees with, or is missing from,
        *checksums* fails the build closed.
        """
        for pkg in self.packages:
            if not pkg.checksum:
                continue
            actual = checksums.get(pkg.vlnv)
            if actual is None:
                raise LockfileError(f"No checksum provided for locked package {pkg.vlnv}.")
            if actual != pkg.checksum:
                raise LockfileError(
                    f"Checksum mismatch for {pkg.vlnv}: locked {pkg.checksum}, got {actual}."
                )

    def matches_resolution(self, resolution: Resolution) -> bool:
        """True if this lockfile pins exactly the VLNVs that *resolution* selected."""
        locked = tuple(sorted(str(p.vlnv) for p in self.packages))
        resolved = tuple(str(v) for v in resolution.vlnvs)
        return locked == resolved


def lock_satisfies_manifest(manifest: Manifest, lock: Lockfile) -> bool:
    """True if every direct dependency in *manifest* is met by a package in *lock*.

    A registry-free freshness check used to decide whether a plain ``install`` can build
    straight from an existing ``ip.lock``: for each ``[dependencies]`` entry there must be a
    locked package with the same ref whose version satisfies the constraint. It catches the
    common ways a lock goes stale against an edited manifest -- a dependency *added* to
    ``ip.toml``, or a constraint *changed* so the locked version no longer fits.

    It deliberately does **not** detect a *removed* dependency (the lock would just carry an
    unused package) or a change reachable only transitively, since verifying those needs the
    dependencies' own manifests (a registry). For a strict, reproducible install that pins
    exactly the lock regardless, use ``--locked``.
    """
    locked: dict[PackageRef, list[AnyVersion]] = {}
    for package in lock.packages:
        locked.setdefault(package.vlnv.ref, []).append(package.vlnv.version)
    return all(
        any(dep.constraint.matches(version) for version in locked.get(dep.ref, ()))
        for dep in manifest.dependencies
    )
